/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { LOLAbi } from "./LOLAbi";
export * as factories from "./factories";
export { LOLAbi__factory } from "./factories/LOLAbi__factory";
